# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: "plugin"
        # A file, directory or wildcard pattern that describes what to upload
        path: "D:\\a\\BBCR-Return-Null-BepInEx-Mod\\BBCR-Return-Null-BepInEx-Mod\\BBCR Return Null Mod\\bin\\Debug\\net481\\BBCR_Return_Null_Mod.dll"
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: "plugin"
        # Destination path
        path: "D:\\a\\"
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: "D:\\a\\BBCR_Return_Null_Mod.dll"
        asset_name: "mod.dll"
        asset_content_type: application/zip
